# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b67d0080833cd1a52fbbc0f13a7b5bbc8b9b399f9c848f3600cbf4f8bf2e6757e738b3323ea9cbfce1baefb2f9949949426b28541abf79359f43d55c10c685

test:
  secret_key_base: ec3e8ceb5b9e5a4f118880379dc4c68644f1ff8186af1e0b735d53392d819b83b5ee4867f2bddff293f7893a1a595eb25df10f26c4c8e0c65a4d5594b8514875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
